import fs from 'node:fs';
import path from 'node:path';
import { parse } from 'csv-parse/sync';

import type { PlayerRecord } from './types.js';

/**
 * SquadStore loads and serves player data generated by the Python scraper.
 */
export class SquadStore {
  private dataPath: string;
  private players: PlayerRecord[] = [];

  constructor(dataPath?: string) {
    const defaultPath = path.resolve(process.cwd(), 'data', 'squads_2025_26.csv');
    this.dataPath = dataPath ? path.resolve(dataPath) : defaultPath;
    this.load();
  }

  /**
   * Load player data from CSV into memory.
   */
  load(): void {
    try {
      const csv = fs.readFileSync(this.dataPath, 'utf8');
      const records = parse(csv, {
        columns: true,
        skip_empty_lines: true,
        trim: true,
      }) as Record<string, string>[];

      const normalized = records.map((record) => {
        const normalizedEntries = Object.entries(record).map(([key, value]) => {
          const cleanKey = key.replace(/^\ufeff/, '').trim();
          return [cleanKey, typeof value === 'string' ? value.trim() : value];
        });
        return Object.fromEntries(normalizedEntries) as PlayerRecord;
      });

      this.players = normalized.filter(
        (record) =>
          record.Name &&
          record.Team &&
          record.Country &&
          record.Position &&
          record.League,
      );
      console.log(`✓ Loaded ${this.players.length} players from ${this.dataPath}`);
    } catch (error: any) {
      console.warn(
        `⚠️  Could not load squad data from ${this.dataPath}. Run scripts/fetch_squads.py first.\nReason: ${error.message}`,
      );
      this.players = [];
    }
  }

  /**
   * Get all players.
   */
  getAll(): PlayerRecord[] {
    return this.players;
  }

  /**
   * Simple search with partial matching for any field.
   */
  search(filters: Partial<PlayerRecord>): PlayerRecord[] {
    if (Object.keys(filters).length === 0) {
      return this.players;
    }

    return this.players.filter((player) => {
      return Object.entries(filters).every(([key, value]) => {
        if (!value) {
          return true;
        }
        const fieldValue = player[key as keyof PlayerRecord];
        if (!fieldValue) {
          return false;
        }

        return String(fieldValue).toLowerCase().includes(String(value).toLowerCase());
      });
    });
  }
}

